# Generated by Django 3.1.7 on 2021-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
